### ISSUE TITLE
Show Images?

### ISSUE THREAD

**Issue by avsingh999** [api-ai/apiai-webhook-sample#11]
How Can I show Image??

**Comment by findzaatar** [comment]
@avsingh999 
You'll have to connect a messenger platform (Facebook, Telegram) to Dialogflow in order to display images. All you need to do is to store the image and provide the public URL in the response for the agent. Also, there is this [example](https://medium.com/@adicuco/how-to-add-images-as-responses-34ee952c16cb) and more info in our [docs](https://dialogflow.com/docs/intents/rich-messages#image).
